name: SkibCommon
version: 1.0
main: skibidilandia.SkibCommon
api-version: 26.1.2
description: Plugin principal do servidor Skibidilândia, adicionando comandos e funcionalidades personalizadas.
commands:
  g:
    description: Envia uma mensagem global para todos os jogadores.
    usage: /g <mensagem>
  w:
    description: Envia uma mensagem privada para outro jogador.
    usage: /w <jogador> <mensagem>
  tell:
    description: Envia uma mensagem privada para outro jogador.
    usage: /tell <jogador> <mensagem>
  tpisland:
    description: Teleporta para uma localização aleatória de uma das ilhas.
    usage: /tpisland <ilha>
  minerador:
    description: (Admin) Entrega uma mineradora automática de um nível.
    usage: /minerador dar <1-6> [jogador]
    permission: skib.miner.admin
  blueprint:
    description: Cria e gera construções a partir de blueprints.
    usage: /blueprint <varinha|criar <nome>>
    aliases: [bp]
    permission: skib.blueprint.admin

